# server config
server:
  port: 8081
  session:
    persistent: true
    timeout: 30
  error:
    whitelabel:
      enabled: false

# spring configs
spring:
  # color logging
  output:
    ansi:
      enabled: always
  # static resource path config
  resources:
    static-locations:
      - classpath:/META-INF/resources/
      - classpath:/resources/
      - classpath:/static/
      - classpath:/public/
      - file:C:/xinhuanet/projects/billiegen/metronic/theme/
  # custom favicon
  mvc:
    favicon:
      enabled: false
  # charset
  http:
      encoding:
        enabled: true
        charset: UTF-8
        force: true
  # freemarker config
  freemarker:
    enabled: true
    content-type: text/html
    cache: false
    charset: UTF-8
    template-loader-path: file:C:/xinhuanet/projects/billiegen/metronic/theme/admin_1/
    suffix: .html
    check-template-location: true
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    request-context-attribute: base
    prefer-file-system-access: true
    settings:
      tag_syntax: auto_detect
      boolean_format: true,false
      # date_time_format: yyyy-MM-dd HH:mm:ss
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      number_format: 0.######
      whitespace_stripping: true
  # spring-boot-data-jpa
  jpa:
    database: mysql
    properties:
      hibernate.hbm2ddl.auto: update
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
    show-sql: true
    open-in-view: true
  # datasource
  datasource:
    url: jdbc:mysql://localhost:3306/billiegen?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true

# custom config
billie:
  back:
    path: /admin
  shiro:
    loginUrl: ${billie.back.path}/login
    successUrl: ${billie.back.path}/index
    unauthorizedUrl: /403
    filterChainDefinitionMap:
      /static/**: anon
      /assets/**: anon
      /admin/logout: logout
      /admin/**: authc








