# server config
server:
  port: 8081
  session:
    persistent: true
    timeout: 30
  error:
    whitelabel:
      enabled: false

# spring configs
spring:
  # color logging
  output:
    ansi:
      enabled: always
  # static resource path config
  resources:
    static-locations:
      - classpath:/META-INF/resources/
      - classpath:/resources/
      - classpath:/static/
      - classpath:/public/
      - file:C:/xinhuanet/projects/billiegen/metronic/theme/
  # custom favicon
  mvc:
    favicon:
      enabled: false
  # charset
  http:
      encoding:
        enabled: true
        charset: UTF-8
        force: true
  # freemarker config
  freemarker:
    enabled: true
    content-type: text/html
    cache: false
    charset: UTF-8
    template-loader-path: file:C:/xinhuanet/projects/billiegen/metronic/theme/admin_1/
    suffix: .html
    check-template-location: true
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    request-context-attribute: base
    prefer-file-system-access: true
    settings:
      tag_syntax: auto_detect
      boolean_format: true,false
      # date_time_format: yyyy-MM-dd HH:mm:ss
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      number_format: 0.######
      whitespace_stripping: true
  # spring-boot-data-jpa
  jpa:
    database: mysql
    properties:
      hibernate.hbm2ddl.auto: update
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
    show-sql: true
    open-in-view: true
  # datasource
  datasource:
    druid:
    # JDBC配置
      url: jdbc:mysql://localhost:3306/billiegen?useSSL=false&useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    # 连接池配置
      db-type: mysql
      type: com.alibaba.druid.pool.DruidDataSource
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 监控配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
        session-stat-max-count: 1000
        principal-session-name: user
        principal-cookie-name: user
        profile-enable: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: mrdios
        login-password: balderdasher
        allow: 127.0.0.1
        deny: 192.168.110.110

# custom config
billie:
  back:
    path: /admin
  shiro:
    loginUrl: ${billie.back.path}/login
    successUrl: ${billie.back.path}/index
    unauthorizedUrl: /403
    filterChainDefinitionMap:
      /static/**: anon
      /assets/**: anon
      /admin/login: anon
#      /admin/logout: logout
      /admin/**: user
      /**: anon
    filter-config:
      redirectUrl: ${billie.shiro.loginUrl}








